import Head from "next/head"
import { useEffect, useState } from "react"
import { useGetData } from "../hooks/data"
import { apiRequest } from "../utils/apis"

export default function Home() {
  const { data } = useGetData()

  console.log("data", data)

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>
        <ul>
          {data &&
            data?.map((item, index) => {
              return <li key={index}>{item.DKK_per_kWh}</li>
            })}
        </ul>
      </div>
    </>
  )
}
